apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: url-api-hpa
  namespace: url
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60   # scale when avg CPU > 60%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30   # react to spikes fast
    scaleDown:
      stabilizationWindowSeconds: 300  # don't scale down too quickly