apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: registry.k8s.io/echoserver:1.10
        env:
        - name: RELEASE
          value: "v1"
        ports:
        - containerPort: 8080
