apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  restartPolicy: Never
  containers:
  - name: load
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command:
    - sh
    - -c
    - |
      echo "Starting load against reliable-web service";
      while true; do
        wget -q -O- http://reliable-web > /dev/null;
      done
