replicaCount: 1

image:
  repository: registry.k8s.io/echoserver
  tag: "1.10"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 128Mi

probes:
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
